[package]
name = "narc-rust"
version = "0.1.0"
description = "NARC Project"
authors = ["Cec√≠lia Carneiro <cecilia.carneiroesilva@gmail.com>"]
repository = "https://github.com/ceciliacsilva/narc"

[dependencies]
cortex-m = "0.5.6"
cortex-m-rt = "0.5.3"

[dependencies.stm32l0]
version = "0.2.3"
features = ["stm32l0x1"]

[dependencies.hal]
version = "0.1.0"
path = "../hal"